function CodeDefine() { 
this.def = new Array();
this.def["IsrOverrun"] = {file: "ert_main_c.html",line:19,type:"var"};
this.def["ert_main.c:OverrunFlag"] = {file: "ert_main_c.html",line:20,type:"var"};
this.def["rt_OneStep"] = {file: "ert_main_c.html",line:21,type:"fcn"};
this.def["stopRequested"] = {file: "ert_main_c.html",line:38,type:"var"};
this.def["runModel"] = {file: "ert_main_c.html",line:39,type:"var"};
this.def["main"] = {file: "ert_main_c.html",line:40,type:"fcn"};
this.def["Controller_rtZControl_Out_Bus"] = {file: "Controller_c.html",line:19,type:"var"};
this.def["CONTROL_PARAM"] = {file: "Controller_c.html",line:28,type:"var"};
this.def["CONTROL_EXPORT"] = {file: "Controller_c.html",line:131,type:"var"};
this.def["Controller_B"] = {file: "Controller_c.html",line:141,type:"var"};
this.def["Controller_DW"] = {file: "Controller_c.html",line:144,type:"var"};
this.def["Controller_U"] = {file: "Controller_c.html",line:147,type:"var"};
this.def["Controller_Y"] = {file: "Controller_c.html",line:150,type:"var"};
this.def["Controller.c:Controller_M_"] = {file: "Controller_c.html",line:153,type:"var"};
this.def["Controller_M"] = {file: "Controller_c.html",line:154,type:"var"};
this.def["Controller_step"] = {file: "Controller_c.html",line:157,type:"fcn"};
this.def["Controller_init"] = {file: "Controller_c.html",line:1111,type:"fcn"};
this.def["Controller_terminate"] = {file: "Controller_c.html",line:1209,type:"fcn"};
this.def["B_Controller_T"] = {file: "Controller_h.html",line:45,type:"type"};
this.def["DW_Controller_T"] = {file: "Controller_h.html",line:60,type:"type"};
this.def["ExtU_Controller_T"] = {file: "Controller_h.html",line:66,type:"type"};
this.def["ExtY_Controller_T"] = {file: "Controller_h.html",line:71,type:"type"};
this.def["FMS_Out_Bus"] = {file: "Controller_types_h.html",line:156,type:"type"};
this.def["INS_Out_Bus"] = {file: "Controller_types_h.html",line:193,type:"type"};
this.def["Control_Out_Bus"] = {file: "Controller_types_h.html",line:203,type:"type"};
this.def["struct_HQfLeQtLjxtu3IdJj406WE"] = {file: "Controller_types_h.html",line:213,type:"type"};
this.def["struct_ulVIkLBg2wNIc1YufVcJJE"] = {file: "Controller_types_h.html",line:279,type:"type"};
this.def["struct_rFkegYH72KGOtqmd7lp2k"] = {file: "Controller_types_h.html",line:288,type:"type"};
this.def["P_Controller_T"] = {file: "Controller_types_h.html",line:293,type:"type"};
this.def["RT_MODEL_Controller_T"] = {file: "Controller_types_h.html",line:296,type:"type"};
this.def["Controller_P"] = {file: "Controller_data_c.html",line:20,type:"var"};
this.def["int8_T"] = {file: "rtwtypes_h.html",line:47,type:"type"};
this.def["uint8_T"] = {file: "rtwtypes_h.html",line:48,type:"type"};
this.def["int16_T"] = {file: "rtwtypes_h.html",line:49,type:"type"};
this.def["uint16_T"] = {file: "rtwtypes_h.html",line:50,type:"type"};
this.def["int32_T"] = {file: "rtwtypes_h.html",line:51,type:"type"};
this.def["uint32_T"] = {file: "rtwtypes_h.html",line:52,type:"type"};
this.def["real32_T"] = {file: "rtwtypes_h.html",line:53,type:"type"};
this.def["real64_T"] = {file: "rtwtypes_h.html",line:54,type:"type"};
this.def["real_T"] = {file: "rtwtypes_h.html",line:60,type:"type"};
this.def["time_T"] = {file: "rtwtypes_h.html",line:61,type:"type"};
this.def["boolean_T"] = {file: "rtwtypes_h.html",line:62,type:"type"};
this.def["int_T"] = {file: "rtwtypes_h.html",line:63,type:"type"};
this.def["uint_T"] = {file: "rtwtypes_h.html",line:64,type:"type"};
this.def["ulong_T"] = {file: "rtwtypes_h.html",line:65,type:"type"};
this.def["char_T"] = {file: "rtwtypes_h.html",line:66,type:"type"};
this.def["uchar_T"] = {file: "rtwtypes_h.html",line:67,type:"type"};
this.def["byte_T"] = {file: "rtwtypes_h.html",line:68,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:86,type:"type"};
this.def["schdl_counter"] = {file: "SysTickScheduler_c.html",line:8,type:"var"};
this.def["schdl_counter_max"] = {file: "SysTickScheduler_c.html",line:9,type:"var"};
this.def["SysTickScheduler.c:SysTick_Isr"] = {file: "SysTickScheduler_c.html",line:13,type:"fcn"};
this.def["SysTick_Handler"] = {file: "SysTickScheduler_c.html",line:36,type:"fcn"};
this.def["ARMCM_SysTick_Config"] = {file: "SysTickScheduler_c.html",line:45,type:"fcn"};
this.def["ARMCM_SysTick_Stop"] = {file: "SysTickScheduler_c.html",line:80,type:"fcn"};
this.def["bootloaderBackgroundTask"] = {file: "blapp_support_c.html",line:10,type:"fcn"};
this.def["bootloaderInit"] = {file: "blapp_support_c.html",line:13,type:"fcn"};
this.def["APPDATAPOINTER"] = {file: "blapp_support_c.html",line:21,type:"var"};
this.def["APPDATACOMPLETED"] = {file: "blapp_support_c.html",line:22,type:"var"};
this.def["COMMownerROMmsg"] = {file: "blapp_support_c.html",line:29,type:"var"};
this.def["COMMownerROMmsg"] = {file: "blapp_support_c.html",line:31,type:"var"};
this.def["OkforMemServ"] = {file: "blapp_support_c.html",line:34,type:"var"};
this.def["USART2_IRQHandler"] = {file: "blapp_support_c.html",line:41,type:"fcn"};
this.def["bootloaderInit"] = {file: "blapp_support_c.html",line:47,type:"fcn"};
this.def["Error_Handler"] = {file: "blapp_support_c.html",line:77,type:"fcn"};
this.def["bootloaderBackgroundTask"] = {file: "blapp_support_c.html",line:83,type:"fcn"};
this.def["taskToSchedule"] = {file: "m3m4m4f_multitasking_c.html",line:18,type:"var"};
this.def["PendSV_Handler"] = {file: "m3m4m4f_multitasking_c.html",line:20,type:"fcn"};
this.def["SVC_Handler"] = {file: "m3m4m4f_multitasking_c.html",line:57,type:"fcn"};
this.def["pulStack"] = {file: "startup_stm32f4xx_c.html",line:18,type:"var"};
this.def["__main"] = {file: "startup_stm32f4xx_c.html",line:19,type:"fcn"};
this.def["Default_ResetHandler"] = {file: "startup_stm32f4xx_c.html",line:137,type:"fcn"};
this.def["startup_stm32f4xx.c:Default_Handler"] = {file: "startup_stm32f4xx_c.html",line:177,type:"fcn"};
this.def["stm32f4xx_init_board"] = {file: "stm32f4xx_init_board_c.html",line:7,type:"fcn"};
this.def["_close"] = {file: "syscalls_stm32f4xx_c.html",line:13,type:"fcn"};
this.def["_fstat"] = {file: "syscalls_stm32f4xx_c.html",line:18,type:"fcn"};
this.def["_isatty"] = {file: "syscalls_stm32f4xx_c.html",line:24,type:"fcn"};
this.def["_lseek"] = {file: "syscalls_stm32f4xx_c.html",line:29,type:"fcn"};
this.def["_open"] = {file: "syscalls_stm32f4xx_c.html",line:34,type:"fcn"};
this.def["_read"] = {file: "syscalls_stm32f4xx_c.html",line:39,type:"fcn"};
this.def["_exit"] = {file: "syscalls_stm32f4xx_c.html",line:44,type:"fcn"};
this.def["heap_end"] = {file: "syscalls_stm32f4xx_c.html",line:52,type:"var"};
this.def["_sbrk"] = {file: "syscalls_stm32f4xx_c.html",line:53,type:"fcn"};
this.def["_write"] = {file: "syscalls_stm32f4xx_c.html",line:74,type:"fcn"};
this.def["_unlink"] = {file: "syscalls_stm32f4xx_c.html",line:79,type:"fcn"};
this.def["SystemCoreClock"] = {file: "system_stm32f4xx_c.html",line:84,type:"var"};
this.def["AHBPrescTable"] = {file: "system_stm32f4xx_c.html",line:86,type:"var"};
this.def["SystemInit"] = {file: "system_stm32f4xx_c.html",line:93,type:"fcn"};
this.def["SystemCoreClockUpdate"] = {file: "system_stm32f4xx_c.html",line:135,type:"fcn"};
this.def["system_stm32f4xx.c:SetSysClock"] = {file: "system_stm32f4xx_c.html",line:184,type:"fcn"};
this.def["SystemInit_ExtMemCtl"] = {file: "system_stm32f4xx_c.html",line:271,type:"fcn"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "\\";
var isPC = true;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["ert_main_c.html"] = "../ert_main.c";
	this.html2Root["ert_main_c.html"] = "ert_main_c.html";
	this.html2SrcPath["Controller_c.html"] = "../Controller.c";
	this.html2Root["Controller_c.html"] = "Controller_c.html";
	this.html2SrcPath["Controller_h.html"] = "../Controller.h";
	this.html2Root["Controller_h.html"] = "Controller_h.html";
	this.html2SrcPath["Controller_private_h.html"] = "../Controller_private.h";
	this.html2Root["Controller_private_h.html"] = "Controller_private_h.html";
	this.html2SrcPath["Controller_types_h.html"] = "../Controller_types.h";
	this.html2Root["Controller_types_h.html"] = "Controller_types_h.html";
	this.html2SrcPath["Controller_data_c.html"] = "../Controller_data.c";
	this.html2Root["Controller_data_c.html"] = "Controller_data_c.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["rtmodel_h.html"] = "../rtmodel.h";
	this.html2Root["rtmodel_h.html"] = "rtmodel_h.html";
	this.html2SrcPath["MW_target_hardware_resources_h.html"] = "../MW_target_hardware_resources.h";
	this.html2Root["MW_target_hardware_resources_h.html"] = "MW_target_hardware_resources_h.html";
	this.html2SrcPath["SysTickScheduler_c.html"] = "file:///C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/armcortexmbase/scheduler/src/SysTickScheduler.c";
	this.html2Root["SysTickScheduler_c.html"] = "SysTickScheduler_c.html";
	this.html2SrcPath["blapp_support_c.html"] = "file:///C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/stm32f4discovery/src/blapp_support.c";
	this.html2Root["blapp_support_c.html"] = "blapp_support_c.html";
	this.html2SrcPath["m3m4m4f_multitasking_c.html"] = "file:///C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/armcortexmbase/scheduler/src/m3m4m4f_multitasking.c";
	this.html2Root["m3m4m4f_multitasking_c.html"] = "m3m4m4f_multitasking_c.html";
	this.html2SrcPath["mw_cmsis_h.html"] = "../mw_cmsis.h";
	this.html2Root["mw_cmsis_h.html"] = "mw_cmsis_h.html";
	this.html2SrcPath["startup_stm32f4xx_c.html"] = "file:///C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/stm32f4discovery/src/startup_stm32f4xx.c";
	this.html2Root["startup_stm32f4xx_c.html"] = "startup_stm32f4xx_c.html";
	this.html2SrcPath["stm32f4xx_init_board_c.html"] = "file:///C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/stm32f4discovery/src/stm32f4xx_init_board.c";
	this.html2Root["stm32f4xx_init_board_c.html"] = "stm32f4xx_init_board_c.html";
	this.html2SrcPath["syscalls_stm32f4xx_c.html"] = "file:///C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/stm32f4discovery/src/syscalls_stm32f4xx.c";
	this.html2Root["syscalls_stm32f4xx_c.html"] = "syscalls_stm32f4xx_c.html";
	this.html2SrcPath["system_stm32f4xx_c.html"] = "file:///C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/stm32f4discovery/src/system_stm32f4xx.c";
	this.html2Root["system_stm32f4xx_c.html"] = "system_stm32f4xx_c.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"ert_main_c.html","Controller_c.html","Controller_h.html","Controller_private_h.html","Controller_types_h.html","Controller_data_c.html","rtwtypes_h.html","rtmodel_h.html","MW_target_hardware_resources_h.html","SysTickScheduler_c.html","blapp_support_c.html","m3m4m4f_multitasking_c.html","mw_cmsis_h.html","startup_stm32f4xx_c.html","stm32f4xx_init_board_c.html","syscalls_stm32f4xx_c.html","system_stm32f4xx_c.html"];
